name: Tests
on:
  push:
    branches:
      - main
  pull_request: {}
  workflow_dispatch: {}
jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.12', '3.13']

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
            version: "latest"
            python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync

      - name: Output installed packages
        run: |
          uv pip freeze

      - name: Output dependency tree
        run: |
          uv pip install pipdeptree
          uv run pipdeptree

      - name: Run Test
        run: uv run pytest tests
